### ISSUE TITLE
Cant add task

### ISSUE THREAD

**Issue by Vallefor** [pydio/cells-sync#11]
I compliled and installcells server. It successfuly run and I can go to webinterface.
My internal addres is: 192.168.1.112:8012
My external address: https://cells.example.com:8002 (I use nginx proxy with config https://pydio.com/en/docs/kb/devops/running-cells-behind-nginx-reverse-proxy ). Also I have Let's Enctypt certificates path in my nginx config.

My cells server run at my home server. I opened port 8002 at my router, so I can browse my cells-server from internet.

I compiled cells-sync from github (also build ux).
Run ./cells-sync start and successfuly added my server at account tab.

But when I try to add task and select my remote folder I receive an error:
the gRPC port may not be correctly opened in the server

I use 'netstat -nputw | grep cells' to discover port and found out that it is an 38191. So, I opened it at my router but then I receive another error:
transport: authentication handshake failed: tls: first record does not look like a TLS handshake

So, I do not know how to fix it.

**Comment by cdujeu** [comment]
Hi @Vallefor 
Thanks for testing (and reporting!). As stated in the release note https://github.com/pydio/cells-dist/blob/master/resources/v2.0.0-rc2/Pydio%20Cells%202.0%20Release%20Candidate.md (we still have to update the official doc when the 2.0 is out), the https => http scenario will not work in that case. 
In that case, the simplest is to enable SSL on the Cells node as well (easy using self-signed mode), and make sure your proxy is https => https, with "insecure skip verify" setup so that the proxy is ok to connect to the underlying self-signed server.

**Comment by Vallefor** [comment]
Thanks for your answer, @cdujeu !

I fully reinstall (droped database, delete .config, .cache, .local) cells via ./cells install using selfsigned cert option.
To nginx config I add "proxy_ssl_verify off;" and changed address to https://192.168.1.112:8012 (instead of http).

Now my web interface starts to loading but then stops and in cells log I see:
ERROR   pydio.rest.frontend     Ladon blocked POST request at /frontend/session. Ladon Response: DefaultDeny:true

So... stiil no success :(

**Comment by cdujeu** [comment]
mmm, must be another issue now - no specific errors in the logs while installing? The external url is still https://cells.example.com:8002   ?

**Comment by Vallefor** [comment]
No, there are was no errors.

I continued my experiments and use your binnary file:
https://download.pydio.com/pub/cells/release/2.0.0-rc2/linux-amd64/cells
And I get another error (do not remember exacly, but it was something like: that cert dont match any name, but expect to match cells.example.com).

Then I used command: `cells config ssl mode` and pointed cells to my existing Let's Encrypt certs. And now everything works as expected.

The main my problem here was that cells need http/2 support, and http/2 need ssl, but nginx cant proxy pass http/2. But when I use valid https domain with nginx + self-signed certificate - cells-sync throws errors.

**Comment by cdujeu** [comment]
So what you exactly mean is 
nginx cant proxy pass http/2 + SSL *self-signed* , but needs a valid SSL config ?

**Comment by Vallefor** [comment]
I mean that in ordinary conditions I can just proxy requests from nginx to Cells Server (like I do with all my services). But gRPC need http/2 and nginx can't do it. https://trac.nginx.org/nginx/ticket/923
It just first time I needed to proxy exacly http/2 and I do not knowed that nginx can't do it.

In my experiments, the best and bulletproof config is to just use Let's Encrypt certeficates, do not use proxy and if you need to setup firewall, router or whatever - use PYDIO_GRPC_EXTERNAL.

I do not know why self-signed cert for gRPC and Let's Encrypt cert for http/1 (with nginx proxy) do not worked for me.

**Comment by jthabet** [comment]
@Vallefor Could you try with the following instructions;
make sure that you have SSL on Cells and on the Reverse proxy.

[nginx_reverse_proxy.pdf](https://github.com/pydio/cells-sync/files/3784576/nginx_reverse_proxy.pdf)

**Comment by Vallefor** [comment]
@jthabet thanks!
With grpc_pass I managed to setup cells with self-signed certs and user nginx as reverse proxy.

But the one thing was a little hard. If you run nginx and cells on same network with same IP you will see "Address already in use". So, you need to setup virtual network, use port forwarding on router or something else. But this problem disapears if you run cells in docker.

I think it is extreamly needed to add option --grpc_internal.
So you can use  --grpc_external=8003 --grpc_internal=8013.

**Comment by jthabet** [comment]
Hello @Vallefor,

If you are running Cells and Nginx on the same server/network, try to bind Cells(internal_url) to localhost.
