### ISSUE TITLE
Selective Sync: Script Error on Windows

### ISSUE THREAD

**Issue by tbleiker** [pydio/cells-sync#17]
When I enable "Selective Sync" on my Windows 10 notebook, I get "Script Error" Dialog:
```
Fehler: Die Eigenschaft für ein nicht erweiterbares Objekt kann nicht erstellt werden.
Code: 0
URL: http://localhost:3636/static/js/2.d4176e9b.chunk.js
```
Sorry, the error is in German. If I open the ui in the browser, I can enable selective sync and the "Select Folder(s)" button appears.

**Comment by cdujeu** [comment]
Thanks @tbleiker 
IE 11 issue... (the webview is using ie11)

**Comment by spentus** [comment]
I have the same error
![image](https://user-images.githubusercontent.com/35918689/71450530-c4394a80-2774-11ea-98ed-5d6e8581e6d4.png)
