### ISSUE TITLE
How to install CEC for windows?

### ISSUE THREAD

**Issue by kirajesus** [pydio/cells-sync#55]
Hi sir @cdujeu. Can you guide me on how to install the CEC for windows? I've tried to launch the application but it says "this is a command line tool, you need to run cmd and run it from there".

Thank you so much!

**Comment by bsinou** [comment]
Hi @kirajesus 

You're at the wrong place.
The cec repository is at https://github.com/pydio/cells-client

_but_ you should really ask such question in the [forum](https://forum.pydio.com)
